name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - cmd/**
      - internal/**
      - go.*
      - .github/workflows/build.yaml
  push:
    branches:
      - main
    paths:
      - cmd/**
      - internal/**
      - go.*
      - .github/workflows/build.yaml

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run tests
        env:
          # Use the toolchain specified in go.mod, or newer
          GOTOOLCHAIN: auto
        run: go test -v ./...

  build:
    name: Build srdl
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build srdl
        run: go build -o srdl cmd/srdl/*.go

  build-sub:
    name: Build srdl-sub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build srdl-sub
        env:
          # Use the toolchain specified in go.mod, or newer
          GOTOOLCHAIN: auto
        run: go build -o srdl-sub cmd/srdl-sub/*.go
