name: Build Docker image

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - main
    paths:
      - .dockerignore
      - Dockerfile
      - cmd/**
      - internal/**
      - go.*
      - .github/workflows/docker.yaml

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Determine tag
        id: determine_tag
        run: |
          TAG="${{ (github.ref_type == 'tag' && github.ref_name) || 'latest' }}"
          echo "tag=${TAG#v}" >> "$GITHUB_OUTPUT"

      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/alexgustafsson/srdl:${{ steps.determine_tag.outputs.tag }}
          labels: |
            org.opencontainers.image.title=srdl
            org.opencontainers.image.description=srdl allows you to easily archive programs from SR.
            org.opencontainers.image.source=https://github.com/AlexGustafsson/srdl
            org.opencontainers.image.version=latest
            org.opencontainers.image.licenses=MIT
